### ISSUE TITLE
Build failed on OS X 10.10, 10.11

### ISSUE THREAD

**Issue by apjanke** [libtom/libtomcrypt#82]
The last libtomcrypt release, 0.42.0, fails to build on OS X 10.10 Yosemite and OS X 10.11.

```
[~/tmp/libtom/libtomcrypt-1.17]
$ uname -a
Darwin spiffy-elcap.local 15.0.0 Darwin Kernel Version 15.0.0: Tue Sep 22 20:33:10 PDT 2015; root:xnu-3247.10.11.1.1~1/RELEASE_X86_64 x86_64
[~/tmp/libtom/libtomcrypt-1.17]
$ make
cc -c -I./testprof/ -I./src/headers/ -Wall -Wsign-compare -W -Wshadow -Wno-unused-parameter -DLTC_SOURCE -O3 -funroll-loops -fomit-frame-pointer -DENCRYPT_ONLY -c src/ciphers/aes/aes.c -o src/ciphers/aes/aes_enc.o
In file included from src/ciphers/aes/aes.c:33:
In file included from ./src/headers/tomcrypt.h:67:
./src/headers/tomcrypt_macros.h:269:24: error: constraint 'I' expects an integer constant expression
      :"0" (word),"I" (i));
                       ^
./src/headers/tomcrypt_macros.h:277:24: error: constraint 'I' expects an integer constant expression
      :"0" (word),"I" (i));
                       ^
./src/headers/tomcrypt_macros.h:368:24: error: constraint 'J' expects an integer constant expression
      :"0" (word),"J" (i));
                       ^
./src/headers/tomcrypt_macros.h:376:24: error: constraint 'J' expects an integer constant expression
      :"0" (word),"J" (i));
                       ^
4 errors generated.
make: *** [src/ciphers/aes/aes_enc.o] Error 1
[✘ ~/tmp/libtom/libtomcrypt-1.17]
$
```

It appears to be fixed in the development head: building from a clone of the GitHub repo succeeds on 10.11.

Encountered this with the Homebrew formula for libtomcrypt, which is currently failing on 10.10 and 10.11. homebrew/homebrew#43906

Could we get a release to fix this?

**Comment by dunn** [comment]
Can the fixes be backported to the stable build?

**Comment by alepuccetti** [comment]
Fixing this would be great

**Comment by osdiab** [comment]
Is this ever going to be fixed?

**Comment by dunn** [comment]
If you'd like to try backporting the fixes, that'd be great!  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

Upstream ticket re: a new release: https://github.com/libtom/libtomcrypt/issues/110

**Comment by MMI** [comment]
We (bitkeeper.com) have put forward a proposed solution in this [pull request](https://github.com/libtom/libtomcrypt/pull/125l)

**Comment by justinclift** [comment]
The commit where building starts working again is this: https://github.com/libtom/libtomcrypt/commit/62878de0c5dbb9f89474590d953bbdb339bd2f76

In the develop branch, any of the commits from 1.17 release up until the commit before that fail.  From that commit onwards, it compiles ok (on OSX 10.11.6 at least).

That commit doesn't cleanly apply to the 1.17 (last official release) source though, so either backporting or more investigation is needed.

**Comment by justinclift** [comment]
For anyone interested, this has been included into an updated PR for Homebrew: https://github.com/Homebrew/homebrew-core/pull/3922

**Comment by karel-m** [comment]
Closing as suggested 2 weeks ago.

**Comment by apjanke** [comment]
I can confirm this issue is fixed on the `develop` branch. However, there's still a build issue with the libtomcrypt 1.18 Release Candidate on macOS. https://github.com/libtom/libtomcrypt/issues/281.

If y'all are interested in getting libtomcrypt running on macOS again, hop on over to upstream, try out their Release Candidate, and report bugs there.

**Comment by flowher** [comment]
Same problem when compiling on Linux with clang

```
../libtomcrypt/src/headers/tomcrypt_macros.h:269:24: error: constraint 'I' expects an integer constant expression
      :"0" (word),"I" (i));

> git log -1
commit bd7933cc2b43ebe7c4349614c6cf1271251ebee4 (HEAD -> master, origin/master)
```

**Comment by rofl0r** [comment]
clang++ ? you're compiling C code with a C++ compiler ?

**Comment by flowher** [comment]
No, I'm compiling C++ code which includes libtomcrypt headers with clang++
